name = "CJC"
author = "Chen Jicheng"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe4f947aa930eb191d8dc8fe688cfff7e391526c541eace8026f68b6efb82ce7"

[versions]
fabric = "0.19.5"
minecraft = "1.21.11"
