name = "CJC"
author = "Chen Jicheng"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "648a6354de86fc6b720f610410c9480f81d71dc8496729b4d7264685799eb0e9"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
