name = "CJC"
author = "Chen Jicheng"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79ca753b4c18312338ae9fd6846c2e5d0123f4336b4721d90b7f3157663d4ec8"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
